# Generated by Django 5.1.1 on 2024-10-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandyType',
            fields=[
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
                ('data_source', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Candy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='candy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.candytype'),
        ),
    ]
