# Generated by Django 5.1.1 on 2024-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candytype_destination_name_alter_destination_candy'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
