# Generated by Django 5.1.1 on 2024-10-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_destination_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='candytype',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='candy_logos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='has_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
