# Generated by Django 5.1.1 on 2024-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candytype_logo_alter_ticket_has_boarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boarding_pass_preview',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_passes'),
        ),
    ]
