# Generated by Django 5.1.1 on 2024-10-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket_boarding_pass_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tsa_precheck',
            new_name='standby',
        ),
    ]
