# Generated by Django 5.1.1 on 2024-10-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_tsa_precheck_ticket_standby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='boarding_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
